spring:
  application:
    name: assignment1

  devtools:
      restart:
          enabled: true

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:2112/assignment1_new
    username: postgres
    password: 29C1_57000

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none

server:
  port: ${PORT:8080}