spring:
  application:
    name: assignment1

  devtools:
      restart:
          enabled: true

  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/test-db}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:default}

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none

server:
  port: ${PORT:8080}
